;;; simplicity-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from simplicity-theme.el

(eval-and-compile (defcustom simplicity-override-colors-alist 'nil "Place to override default theme colors.

You can override a subset of the theme's default colors by
defining them in this alist." :group 'simplicity-theme :type '(alist :key-type (string :tag "Name") :value-type (string :tag " Hex"))))
(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))) (when (not window-system) (custom-set-faces '(default ((t (:background nil)))))))
(register-definition-prefixes "simplicity-theme" '("simplicity"))

;;; End of scraped data

(provide 'simplicity-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; simplicity-theme-autoloads.el ends here
